import rawCards from '../data/game-content.json';
import rawBalance from '../data/balance.json';
import {
  BalanceSchema,
  BOUNDS,
  ContentFileSchema,
  METRICS,
  validateContentSet,
  type Balance,
  type Bound,
  type Card,
  type Metric,
} from '../types/content';

export interface GameData {
  /** Tutorial card(s) for the first run of the session. */
  intro: Card[];
  /** Start card(s) for later runs. */
  start: Card[];
  regular: Card[];
  gameover: Record<Metric, Record<Bound, Card[]>>;
  /** End cards keyed by month band. */
  endBands: Card[];
  /** End card(s) shown when the deck runs out. */
  endExhausted: Card[];
  balance: Balance;
}

/**
 * Content is generated by `pnpm run content` into src/data/ and bundled by Vite,
 * so code and content always ship together. We still re-validate here (schema +
 * cross-card rules) so malformed data fails fast with a readable message
 * instead of crashing mid-play.
 */
export function loadGameData(): GameData {
  const balance = BalanceSchema.safeParse(rawBalance);
  if (!balance.success) throw new Error(`Invalid balance.json:\n${balance.error.message}`);

  const cards = ContentFileSchema.safeParse(rawCards);
  if (!cards.success) throw new Error(`Invalid game-content.json:\n${cards.error.message}`);

  const set = validateContentSet(cards.data, balance.data);
  if (set.errors.length > 0) throw new Error(`Invalid game content:\n• ${set.errors.join('\n• ')}`);
  for (const w of set.warnings) console.warn(`Content: ${w}`);

  const all = cards.data;
  const starts = all.filter((c) => c.type === 'start');
  const first = starts.filter((c) => c.startKind === 'first');
  const again = starts.filter((c) => c.startKind === 'again');

  const gameover = {} as GameData['gameover'];
  for (const m of METRICS) {
    gameover[m] = {} as Record<Bound, Card[]>;
    for (const b of BOUNDS) gameover[m][b] = all.filter((c) => c.gameover?.metric === m && c.gameover.bound === b);
  }

  return {
    intro: first.length > 0 ? first : starts,
    start: again.length > 0 ? again : starts,
    regular: all.filter((c) => c.type === 'regular'),
    gameover,
    endBands: all.filter((c) => c.end && 'minMonths' in c.end),
    endExhausted: all.filter((c) => c.end && 'exhausted' in c.end),
    balance: balance.data,
  };
}
