import rawItems from '../data/game-content.json';
import rawBalance from '../data/balance.json';
import { BalanceSchema, ContentFileSchema, type Balance, type ContentItem } from '../types/content';

export interface GameData {
  items: ContentItem[];
  balance: Balance;
}

/**
 * Content is generated by `pnpm run content` into src/data/ and bundled by Vite,
 * so code and content always ship together (no stale-cache mismatch, no fetch).
 * We still re-validate here so malformed data fails fast with a readable message
 * instead of crashing mid-play.
 */
export function loadGameData(): GameData {
  const items = ContentFileSchema.safeParse(rawItems);
  if (!items.success) throw new Error(`Invalid game-content.json:\n${items.error.message}`);

  const balance = BalanceSchema.safeParse(rawBalance);
  if (!balance.success) throw new Error(`Invalid balance.json:\n${balance.error.message}`);

  return { items: items.data, balance: balance.data };
}
